export const inputs = [
    {
      name: "nome",
      id: "nome",
      label: "Nome Completo",
      placeholder: "Digite seu nome Completo",
      value: "",
      type: "text",
      required: true,
      tamanho: 56,
      valid : true,
      disabled : false,
    },
    {
      name: "cargo",
      id: "cargo",
      label: "Cargo",
      placeholder: "Digite o Cargo",
      value: "",
      type: "text",
      required: true,
      tamanho: 56,
      valid : true,
      disabled : false,
    },
    {
      name: "dataNascimento",
      id: "dataNascimento",
      label: "Data Nascimento",
      placeholder: "Data Nascimento",
      value: "",
      type: "text",
      required: true,
      tamanho: 34,
      valid : true,
      disabled : false,
    },
    {
      name: "CPF",
      id: "CPF",
      label: "CPF",
      placeholder: "CPF",
      value: "",
      type: "text",
      required: true,
      tamanho: 34,
      valid : true,
      disabled : false,
    },
    {
      name: "RG",
      id: "RG",
      label: "RG",
      placeholder: "RG",
      value: "",
      type: "text",
      required: true,
      tamanho: 34,
      valid : true,
      disabled : false,
    },
    {
      name: "celular",
      id: "celular",
      label: "Celular",
      placeholder: "Celular",
      value: "",
      type: "tel",
      required: true,
      tamanho: 34,
      valid : true,
      disabled : false,    
    },];

export const inputsLogin = [
    {
      name: "login",
      id: "login",
      label: "Login",
      placeholder: "Login",
      value: "",
      type: "text",
      required: true,
      tamanho: 56,
      valid : true,
      disabled : false,

    },
    {
      name: "senha",
      id: "senha",
      label: "Senha",
      placeholder: "Senha",
      value: "",
      type: "password",
      required: true,
      tamanho: 56,
      valid : true,
      disabled : false,

    },
    
  ];

  export const buscarUsuario = [
    {
      name: "BuscarUsuario",
      id: "BuscarUsuario",
      label: "Selecione um Usuario",
      placeholder: "Selecione um Usuario",
      value: "",
      required: true,
      tamanho: 120,
      valid : true,
      disabled : false,

    },
  ];
