export const inputs = [
  {
    name: "razaoSocial",
    id: "razaoSocial",
    label: "Razão Social",
    placeholder: "Razão Social",
    value: "",
    type: "text",
    required: true,
    classe: "input_tamanho1",
    valid : true,
    disabled : true,
  },
  {
    name: "nomeFantasia",
    id: "nomeFantasia",
    label: "Nome Fantasia",
    placeholder: "Nome Fantasia",
    value: "",
    type: "text",
    required: true,
    classe: "input_tamanho2",
    valid : true,
    disabled : true,
  },
  {
    name: "CNPJ",
    id: "CNPJ",
    label: "CNPJ",
    placeholder: "CNPJ",
    value: "",
    type: "text",
    required: true,
    classe: "input_tamanho2",
    valid : true,
    disabled : true,
  },
  {
    name: "telefone",
    id: "telefone",
    label: "Telefone",
    placeholder: "Telefone",
    value: "",
    type: "tel",
    required: false,
    classe: "input_tamanho3",
    valid : true,
    disabled : true,
  },
  {
    name: "celular",
    id: "celular",
    label: "Celular",
    placeholder: "Celular",
    value: "",
    type: "tel",
    required: false,
    classe: "input_tamanho3",
    valid : true,
    disabled : true,
  },
  {
    name: "site",
    id: "site",
    label: "Site",
    placeholder: "Site",
    value: "",
    type: "url",
    required: false,
    classe: "input_tamanho3",
    valid : true,
    disabled : true,
  },
  {
    name: "representante",
    id: "representante",
    label: "Representante",
    placeholder: "Representante",
    value: "",
    type: "text",
    required: false,
    classe: "input_tamanho3",
    valid : true,
    disabled : true,

  },
  {
    name: "celularRepresentante",
    id: "celularRepresentante",
    label: "Celular Representante",
    placeholder: "Celular Representante",
    value: "",
    type: "tel",
    required: false,
    classe: "input_tamanho3",
    valid : true,
    disabled : true,

  },
  {
    name: "emailRepresentante",
    id: "emailRepresentante",
    label: "Email Representante",
    placeholder: "Email Representante",
    value: "",
    type: "email",
    required: true,
    classe: "input_tamanho3",
    valid : true,
    disabled : true,

  },];

export const inputsEndereco = [
  {
    name: "CEP",
    id: "CEP",
    label: "CEP",
    placeholder: "CEP",
    value: "",
    type: "text",
    required: true,
    classe: "input_tamanho4",
    valid : true,
    disabled : true,

  },
  {
    name: "nomeLogradouro",
    id: "nomeLogradouro",
    label: "Nome da Rua / Avenida",
    placeholder: "Nome da Rua / Avenida",
    value: "",
    type: "text",
    required: true,
    classe: "input_tamanho2",
    valid : true,
    disabled : true,

  },
  {
    name: "numero",
    id: "numero",
    label: "Número",
    placeholder: "Número",
    value: "",
    type: "text",
    required: true,
    classe: "input_tamanho4",
    valid : true,
    disabled : true,

  },
  {
    name: "complemento",
    id: "complemento",
    label: "Complemento",
    placeholder: "Complemento",
    value: "",
    type: "text",
    required: true,
    classe: "input_tamanho4",
    valid : true,
    disabled : true,

  },
  {
    name: "bairro",
    id: "bairro",
    label: "Bairro",
    placeholder: "Bairro",
    value: "",
    type: "text",
    required: true,
    classe: "input_tamanho4",
    valid : true,
    disabled : true,

  },
  {
    name: "cidade",
    id: "cidade",
    label: "Cidade",
    placeholder: "Cidade",
    value: "",
    type: "text",
    required: true,
    classe: "input_tamanho4",
    valid : true,
    disabled : true,

  },
  {
    name: "estado",
    id: "estado",
    label: "Estado",
    placeholder: "Estado",
    value: "",
    type: "text",
    required: true,
    classe: "input_tamanho4",
    valid : true,
    disabled : true,

  },
];

export const buscarFornecedor = [
  {
    name: "BuscarFornecedor",
    id: "BuscarFornecedor",
    label: "Selecione um Fornecedor",
    placeholder: "Selecione um fornecedor",
    value: "",
    required: true,
    classe: "input_tamanho1",
    valid : true,
    disabled : false,

  },
];
