export const inputs = [
    {
      name: "razaoSocial",
      id: "razaoSocial",
      label: "Razão Social",
      placeholder: "Razão Social",
      value: "",
      type: "text",
      required: true,
      tamanho: 120,
      valid : true,
      disabled : false,
    },
    {
      name: "nomeFantasia",
      id: "nomeFantasia",
      label: "Nome Fantasia",
      placeholder: "Nome Fantasia",
      value: "",
      type: "text",
      required: true,
      tamanho: 56,
      valid : true,
      disabled : false,
    },
    {
      name: "CNPJ",
      id: "CNPJ",
      label: "CNPJ",
      placeholder: "CNPJ",
      value: "",
      type: "text",
      required: true,
      tamanho: 56,
      valid : true,
      disabled : false,
    },
    {
      name: "telefone",
      id: "telefone",
      label: "Telefone",
      placeholder: "Telefone",
      value: "",
      type: "tel",
      required: false,
      tamanho: 34,
      valid : true,
      disabled : false,
    },
    {
      name: "celular",
      id: "celular",
      label: "Celular",
      placeholder: "Celular",
      value: "",
      type: "tel",
      required: false,
      tamanho: 34,
      valid : true,
      disabled : false,
    },
    {
      name: "site",
      id: "site",
      label: "Site",
      placeholder: "Site",
      value: "",
      type: "url",
      required: false,
      tamanho: 34,
      valid : true,
      disabled : false,
    },
    {
      name: "representante",
      id: "representante",
      label: "Representante",
      placeholder: "Representante",
      value: "",
      type: "text",
      required: false,
      tamanho: 34,
      valid : true,
      disabled : false,

    },
    {
      name: "celularRepresentante",
      id: "celularRepresentante",
      label: "Celular Representante",
      placeholder: "Celular Representante",
      value: "",
      type: "tel",
      required: false,
      tamanho: 34,
      valid : true,
      disabled : false,

    },
    {
      name: "emailRepresentante",
      id: "emailRepresentante",
      label: "Email Representante",
      placeholder: "Email Representante",
      value: "",
      type: "email",
      required: true,
      tamanho: 34,
      valid : true,
      disabled : false,

    },];

export const inputsEndereco = [
    {
      name: "CEP",
      id: "CEP",
      label: "CEP",
      placeholder: "CEP",
      value: "",
      type: "text",
      required: true,
      tamanho: 20,
      valid : true,
      disabled : false,

    },
    {
      name: "nomeLogradouro",
      id: "nomeLogradouro",
      label: "Nome da Rua / Avenida",
      placeholder: "Nome da Rua / Avenida",
      value: "",
      type: "text",
      required: true,
      tamanho: 62,
      valid : true,
      disabled : false,

    },
    {
      name: "numero",
      id: "numero",
      label: "Número",
      placeholder: "Número",
      value: "",
      type: "text",
      required: true,
      tamanho: 20,
      valid : true,
      disabled : false,

    },
    {
      name: "complemento",
      id: "complemento",
      label: "Complemento",
      placeholder: "Complemento",
      value: "",
      type: "text",
      required: true,
      tamanho: 23,
      valid : true,
      disabled : false,

    },
    {
      name: "bairro",
      id: "bairro",
      label: "Bairro",
      placeholder: "Bairro",
      value: "",
      type: "text",
      required: true,
      tamanho: 23,
      valid : true,
      disabled : false,

    },
    {
      name: "cidade",
      id: "cidade",
      label: "Cidade",
      placeholder: "Cidade",
      value: "",
      type: "text",
      required: true,
      tamanho: 24,
      valid : true,
      disabled : false,

    },
    {
      name: "estado",
      id: "estado",
      label: "Estado",
      placeholder: "Estado",
      value: "",
      type: "text",
      required: true,
      tamanho: 24,
      valid : true,
      disabled : false,

    },
  ];
